name: Security CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit (SAST)
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json || echo "Bandit completed with warnings"

      - name: Run pip-audit (SCA for Python)
        run: |
          pip install pip-audit
          pip-audit --requirement requirements.txt --json > dependency-check-report.json

      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Upload pip audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.json